<?php

$peliculas = array(
    array(
        "nombre" => "Oppenheimer",
        "imagen_url" => "https://pics.filmaffinity.com/Oppenheimer-828933592-large.jpg",
        "horarios" => array("14:00", "17:00", "20:00"),
        "sinopsis" => "Una crónica de la vida del físico teórico J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica.",
        "duracion" => "180 minutos",
        "director" => "Christopher Nolan",
        "reparto" => array("Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."),
        "calificacion" => "+16",
        "genero" => "Drama, Biografía",
        "trailer_url" => "https://www.youtube.com/watch?v=bK6ldnjE3Y0",
        "valoracion" => "4.7 / 5"
    ),
    array(
        "nombre" => "Avatar: El sentido del agua",
        "imagen_url" => "https://pics.filmaffinity.com/avatar_the_way_of_water-722646748-mmed.jpg",
        "horarios" => array("13:00", "16:30", "21:00"),
        "sinopsis" => "Jake Sully y Neytiri forman una familia y hacen todo lo posible por mantenerse juntos. Sin embargo, deben abandonar su hogar y explorar las regiones de Pandora.",
        "duracion" => "192 minutos",
        "director" => "James Cameron",
        "reparto" => array("Sam Worthington", "Zoe Saldaña", "Sigourney Weaver", "Kate Winslet"),
        "calificacion" => "+12",
        "genero" => "Ciencia ficción, Acción",
        "trailer_url" => "https://www.youtube.com/watch?v=d9MyW72ELq0",
        "valoracion" => "4.0 / 5"
    ),
    array(
        "nombre" => "Spider-Man: No Way Home",
        "imagen_url" => "https://pics.filmaffinity.com/Spider_Man_No_Way_Home-164964839-large.jpg",
        "horarios" => array("15:00", "18:30", "21:30"),
        "sinopsis" => "Peter Parker busca la ayuda de Doctor Strange para hacer que el mundo olvide su identidad secreta, pero las cosas no salen como esperaba.",
        "duracion" => "148 minutos",
        "director" => "Jon Watts",
        "reparto" => array("Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon"),
        "calificacion" => "+12",
        "genero" => "Acción, Superhéroes",
        "trailer_url" => "https://www.youtube.com/watch?v=JfVOs4VSpmA",
        "valoracion" => "4.5 / 5"
    ),
    array(
        "nombre" => "Dune",
        "imagen_url" => "https://pics.filmaffinity.com/Dune-209834814-mmed.jpg",
        "horarios" => array("16:00", "19:00", "22:00"),
        "sinopsis" => "Paul Atreides, un joven brillante y talentoso, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo.",
        "duracion" => "155 minutos",
        "director" => "Denis Villeneuve",
        "reparto" => array("Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Zendaya"),
        "calificacion" => "+13",
        "genero" => "Ciencia ficción, Aventura",
        "trailer_url" => "https://www.youtube.com/watch?v=8g18jFHCLXk",
        "valoracion" => "4.4 / 5"
    ),
    array(
        "nombre" => "Matrix Resurrections",
        "imagen_url" => "https://pics.filmaffinity.com/Matrix_Resurrections-864937945-large.jpg",
        "horarios" => array("13:30", "17:30", "21:30"),
        "sinopsis" => "Neo vive una vida aparentemente normal, pero pronto descubre que su mundo no es lo que parece.",
        "duracion" => "148 minutos",
        "director" => "Lana Wachowski",
        "reparto" => array("Keanu Reeves", "Carrie-Anne Moss", "Yahya Abdul-Mateen II", "Jessica Henwick"),
        "calificacion" => "+16",
        "genero" => "Ciencia ficción, Acción",
        "trailer_url" => "https://www.youtube.com/watch?v=9ix7TUGVYIo",
        "valoracion" => "3.8 / 5"
    ),
    array(
        "nombre" => "El escuadrón suicida",
        "imagen_url" => "https://pics.filmaffinity.com/El_Escuadraon_Suicida-629689677-large.jpg",
        "horarios" => array("14:30", "18:00", "22:30"),
        "sinopsis" => "Un grupo de supervillanos es enviado a una misión peligrosa en una isla controlada por el enemigo.",
        "duracion" => "132 minutos",
        "director" => "James Gunn",
        "reparto" => array("Margot Robbie", "Idris Elba", "John Cena", "Joel Kinnaman"),
        "calificacion" => "+16",
        "genero" => "Acción, Superhéroes",
        "trailer_url" => "https://www.youtube.com/watch?v=JuDLepNa7hw",
        "valoracion" => "4.1 / 5"
    ),
    array(
        "nombre" => "No Time to Die",
        "imagen_url" => "https://pics.filmaffinity.com/Sin_tiempo_para_morir-525355918-large.jpg",
        "horarios" => array("15:30", "19:00", "22:30"),
        "sinopsis" => "James Bond ha dejado el servicio activo, pero su paz se ve interrumpida cuando un viejo amigo de la CIA le pide ayuda.",
        "duracion" => "163 minutos",
        "director" => "Cary Joji Fukunaga",
        "reparto" => array("Daniel Craig", "Léa Seydoux", "Rami Malek", "Ralph Fiennes"),
        "calificacion" => "+13",
        "genero" => "Acción, Espionaje",
        "trailer_url" => "https://www.youtube.com/watch?v=BIhNsAtPbPI",
        "valoracion" => "4.2 / 5"
    ),
    array(
        "nombre" => "Encanto",
        "imagen_url" => "https://pics.filmaffinity.com/Encanto-246546841-large.jpg",
        "horarios" => array("12:00", "14:30", "17:00"),
        "sinopsis" => "Una familia extraordinaria vive en una casa mágica en las montañas de Colombia.",
        "duracion" => "109 minutos",
        "director" => "Jared Bush, Byron Howard",
        "reparto" => array("Stephanie Beatriz", "John Leguizamo", "Diane Guerrero", "Wilmer Valderrama"),
        "calificacion" => "ATP",
        "genero" => "Animación, Familia",
        "trailer_url" => "https://www.youtube.com/watch?v=CaimKeDcudo",
        "valoracion" => "4.6 / 5"
    ),
    array(
        "nombre" => "Shang-Chi y la leyenda de los diez anillos",
        "imagen_url" => "https://m.media-amazon.com/images/M/MV5BZmY5MDcyNzAtYzg3MC00MGNlLTg3OGItNmRjYThkZGVlNzAyXkEyXkFqcGc@._V1_.jpg",
        "horarios" => array("13:00", "16:30", "20:00"),
        "sinopsis" => "Shang-Chi debe enfrentarse al pasado que pensaba haber dejado atrás cuando es arrastrado a la red de la misteriosa organización de los Diez Anillos.",
        "duracion" => "132 minutos",
        "director" => "Destin Daniel Cretton",
        "reparto" => array("Simu Liu", "Awkwafina", "Tony Leung", "Michelle Yeoh"),
        "calificacion" => "+13",
        "genero" => "Acción, Superhéroes",
        "trailer_url" => "https://www.youtube.com/watch?v=8YjFbMbfXaQ",
        "valoracion" => "4.3 / 5"
    ),
    array(
        "nombre" => "Black Panther: Wakanda Forever",
        "imagen_url" => "https://pics.filmaffinity.com/Black_Panther_Wakanda_Forever-869269163-mmed.jpg",
        "horarios" => array("14:30", "18:00", "21:00"),
        "sinopsis" => "Después de la muerte del Rey T'Challa, Wakanda lucha por protegerse de fuerzas externas mientras sus líderes buscan el camino hacia el futuro.",
        "duracion" => "161 minutos",
        "director" => "Ryan Coogler",
        "reparto" => array("Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Winston Duke"),
        "calificacion" => "+13",
        "genero" => "Acción, Superhéroes",
        "trailer_url" => "https://www.youtube.com/watch?v=_Z3QKkl1WyM",
        "valoracion" => "4.1 / 5"
    )
);
